create table if not exists public.feedback_comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 24),
  text text not null check (char_length(text) between 1 and 280),
  created_at timestamptz not null default now()
);

alter table public.feedback_comments drop column if exists is_owner;
alter table public.feedback_comments drop column if exists owner_key;

drop trigger if exists trg_feedback_comments_guard on public.feedback_comments;
drop function if exists public.feedback_comments_guard();

alter table public.feedback_comments enable row level security;

drop policy if exists "feedback_select_all" on public.feedback_comments;
create policy "feedback_select_all"
on public.feedback_comments
for select
to anon
using (true);

drop policy if exists "feedback_insert_anon" on public.feedback_comments;
create policy "feedback_insert_anon"
on public.feedback_comments
for insert
to anon
with check (true);
