create table if not exists public.feedback_comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 24),
  text text not null check (char_length(text) between 1 and 280),
  is_owner boolean not null default false,
  owner_key text,
  created_at timestamptz not null default now()
);

alter table public.feedback_comments add column if not exists is_owner boolean not null default false;
alter table public.feedback_comments add column if not exists owner_key text;

alter table public.feedback_comments enable row level security;

drop policy if exists "feedback_select_all" on public.feedback_comments;
create policy "feedback_select_all"
on public.feedback_comments
for select
to anon
using (true);

drop policy if exists "feedback_insert_anon" on public.feedback_comments;
create policy "feedback_insert_anon"
on public.feedback_comments
for insert
to anon
with check (true);

create or replace function public.feedback_comments_guard()
returns trigger
language plpgsql
as $$
begin
  if lower(new.name) = 'owner' then
    if new.is_owner is distinct from true then
      raise exception 'OWNER requires owner mode';
    end if;
    if coalesce(new.owner_key, '') <> 'baauer01' then
      raise exception 'Invalid owner code';
    end if;
    new.name := 'OWNER';
    new.owner_key := null;
  else
    if new.is_owner is true then
      raise exception 'Only OWNER may use owner mode';
    end if;
    new.owner_key := null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_feedback_comments_guard on public.feedback_comments;
create trigger trg_feedback_comments_guard
before insert on public.feedback_comments
for each row
execute function public.feedback_comments_guard();
